apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName}}
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007